### ISSUE TITLE
Crashes when calling a function with `assert` inside it

### ISSUE THREAD

**Issue by travs** [dapphub/ds-test#4]
[EtherToken.sol](https://gist.github.com/11d37a7de527c8f80fb89c253ebaba4b) contract

[Asset.t.sol](https://gist.github.com/2d10e87e125ba0bade046e5c87d9374b) tests

When I run `dapp test -v` I get this crash error in the output:
```
+ dapp quicktest -v out out/simpleAdapter.bin out/rewards.bin out/safeMath.bin
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Trying out/assets/AssetTest...
.F.

  [CRASH] testWithdraw
                                -> <out/assets/AssetTest#ee35>.testWithdraw() => BadInstruction
    <out/assets/AssetTest#ee35> ->   <out/assets/EtherToken#db93>.balanceOf(<out/assets/AssetTest#ee35>) => (1e+28)
    <out/assets/AssetTest#ee35> ->   <out/assets/EtherToken#db93>.withdraw(0.5 ether) => BadInstruction

2 tests passed, 1 failed
Took 0.200s

```

When I remove the assert on L45 [here](https://gist.github.com/anonymous/11d37a7de527c8f80fb89c253ebaba4b#L45) I don't get this crash.

Could it be something to do with overshadowing solidity's native `assert` function?

**Comment by rainbreak** [comment]
ds-test no longer shadows `assert`, so it probably isn't that. It just looks like your `withdraw` call is failing for whatever reason. Try stripping out all the things that could cause a `throw` and then add them back in one by one.

The output for this kind of thing should improve with our new testing tool, but it isn't ready just yet.

**Comment by travs** [comment]
@rainbreak thank you for the quick response.
You are correct; this was caused by own misunderstanding. `setUp()` is run before *each* test, not once (before all).

Closing this now.
