### ISSUE TITLE
Consider adding a package.json file

### ISSUE THREAD

**Issue by smartcontracts** [dapphub/ds-test#43]
It would be a massive improvement for compatibility with NPM if ds-test had a package.json file. This would make it possible to import ds-test as a GitHub dependency without `npm install` breaking. This would not require actually publishing ds-test to NPM or dealing with the NPM ecosystem beyond just including the one file. forge-std recently made this addition, for what it's worth.

See here for the package.json that forge-std added for reference: https://github.com/foundry-rs/forge-std/blob/master/package.json

**Comment by d-xo** [comment]
Sounds reasonable. Will merge a PR that adds this.

**Comment by smartcontracts** [comment]
@d-xo just getting around to this now, sorry for the delay! Opened #45 to add the package.json file.
