### ISSUE TITLE
Allow for equatlity assertion with tiny margin of errors

### ISSUE THREAD

**Issue by FredCoen** [dapphub/ds-test#44]
Could we add equality assertions that allow for very tiny deviations (due to rounding of different order of fixed math lib operations in expected test values vs source code values) which would be specified in the assert function signature? 

For example something like this:

```
function assertEqWithDeviation(
    uint256 a,
    uint256 b,
    uint256 allowedDeviation
) internal {
    if (a != b) {
        if (a > b) {
            if (a - b > allowedDeviation) {
                fail();
            }
        }
        if (a < b) {
            if (b-a > allowedDeviation) {
                fail();
            }
        }
    }
}
```

**Comment by mds1** [comment]
Note that forge-std has `assertApproxEqAbs` and `assertApproxEqRel` methods you can use https://github.com/foundry-rs/forge-std/blob/2a2ce3692b8c1523b29de3ec9d961ee9fbbc43a6/src/Test.sol#L337-L467

**Comment by FredCoen** [comment]
thanks
